<?php

use Illuminate\Database\Seeder;

class AppAccountsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        DB::statement('SET FOREIGN_KEY_CHECKS = 0;');
        \DB::table('app_accounts')->delete();
        
        \DB::table('app_accounts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'Efectivo $',
                'bank' => '',
                'type' => 3,
                'cbu' => '',
                'number' => '',
                'currency' => '$',
                'notes' => '<p><br></p>',
                'close_pattern' => '',
                'due_pattern' => '',
                'is_active' => 1,
                'created_at' => '2019-08-29 21:03:09',
                'updated_at' => '2019-08-30 10:58:49',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'Efectivo U$S',
                'bank' => '',
                'type' => 3,
                'cbu' => '',
                'number' => '',
                'currency' => 'U$S',
                'notes' => '<p>-</p>',
                'close_pattern' => '',
                'due_pattern' => '',
                'is_active' => 1,
                'created_at' => '2019-08-29 21:03:31',
                'updated_at' => '2019-08-29 21:09:15',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'CA$ Macro Adri',
                'bank' => 'Macro',
                'type' => 1,
                'cbu' => '2850790540094957129338',
                'number' => '479009495712933',
                'currency' => '$',
                'notes' => '<p><br></p>',
                'close_pattern' => '',
                'due_pattern' => '',
                'is_active' => 1,
                'created_at' => '2019-08-29 21:09:07',
                'updated_at' => '2020-03-18 13:09:05',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'entry_id' => 1,
                'plan_id' => 1,
                'name' => 'Visa Platino S',
                'bank' => 'Macro',
                'type' => 4,
                'cbu' => '',
                'number' => '',
                'currency' => '$',
                'notes' => '<p>-</p>',
                'close_pattern' => 'lastThursdayOfMonth',
                'due_pattern' => 'secondMondayOfNextMonth',
                'is_active' => 1,
                'created_at' => '2019-08-30 10:24:06',
                'updated_at' => '2020-04-06 23:14:16',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'Visa Platino U$S',
                'bank' => 'Macro',
                'type' => 4,
                'cbu' => '',
                'number' => '',
                'currency' => 'U$S',
                'notes' => '',
                'close_pattern' => 'lastThursdayOfMonth',
                'due_pattern' => 'secondMondayOfNextMonth',
                'is_active' => 1,
                'created_at' => '2019-08-30 10:26:45',
                'updated_at' => '2020-04-07 22:05:36',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'entry_id' => 33,
                'plan_id' => 38,
                'name' => 'Visa Negra $',
                'bank' => 'Macro',
                'type' => 4,
                'cbu' => '',
                'number' => '',
                'currency' => '$',
                'notes' => '',
                'close_pattern' => 'lastThursdayOfMonth',
                'due_pattern' => 'secondMondayOfNextMonth',
                'is_active' => 1,
                'created_at' => '2019-08-30 10:27:20',
                'updated_at' => '2020-04-07 22:05:38',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'Visa Negra U$S',
                'bank' => 'Macro',
                'type' => 4,
                'cbu' => '',
                'number' => '',
                'currency' => 'U$S',
                'notes' => '',
                'close_pattern' => 'lastThursdayOfMonth',
                'due_pattern' => 'secondMondayOfNextMonth',
                'is_active' => 1,
                'created_at' => '2019-08-30 10:27:41',
                'updated_at' => '2020-04-07 22:05:40',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'CA$ Nación',
                'bank' => 'Nación',
                'type' => 1,
                'cbu' => '0110442830044252972051',
                'number' => '30024425297205',
                'currency' => '$',
                'notes' => NULL,
                'close_pattern' => '',
                'due_pattern' => '',
                'is_active' => 1,
                'created_at' => '2020-03-15 14:55:58',
                'updated_at' => '2020-03-18 13:08:41',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'CA$ Macro Maru',
                'bank' => 'Macro',
                'type' => 1,
                'cbu' => '2850790540095024792628',
                'number' => '479009502479262',
                'currency' => '$',
                'notes' => NULL,
                'close_pattern' => '',
                'due_pattern' => '',
                'is_active' => 1,
                'created_at' => '2020-03-18 13:12:09',
                'updated_at' => '2020-03-18 13:12:09',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'CA$ Galicia Maru',
                'bank' => 'Galicia',
                'type' => 1,
                'cbu' => '00701033 30004157173735',
                'number' => '4157173-7 103-3',
                'currency' => '$',
                'notes' => NULL,
                'close_pattern' => '',
                'due_pattern' => '',
                'is_active' => 1,
                'created_at' => '2020-03-27 19:09:54',
                'updated_at' => '2020-03-27 19:09:54',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'entry_id' => 2,
                'plan_id' => 2,
                'name' => 'Mastercard',
                'bank' => 'Macro',
                'type' => 4,
                'cbu' => '',
                'number' => NULL,
                'currency' => '$',
                'notes' => NULL,
                'close_pattern' => 'nextThurdayAfter18',
                'due_pattern' => 'workingDaysAfterClose',
                'is_active' => 1,
                'created_at' => '2020-03-28 15:07:47',
                'updated_at' => '2020-04-06 23:14:33',
                'created_by' => 1,
                'updated_by' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'entry_id' => NULL,
                'plan_id' => NULL,
                'name' => 'Crédito Toyota',
                'bank' => 'TCFA',
                'type' => 5,
                'cbu' => '',
                'number' => NULL,
                'currency' => '$',
                'notes' => '<p>Préstamo para la compra del Etios</p><p><b>Datos del préstamo:</b></p><p><a href="https://www.toyotacfa.com.ar/toyota-sop-web-cliente/faces/pages/login/index.xhtml">https://www.toyotacfa.com.ar/toyota-sop-web-cliente/faces/pages/login/index.xhtml</a><a href="https://www.toyotacfa.com.ar/toyota-sop-web-cliente/faces/pages/login/index.xhtml"></a></p><p>usuario: mcoloccini@webmind.com.ar</p><p>clave: Colon1256<br><br></p>',
                'close_pattern' => '',
                'due_pattern' => '',
                'is_active' => 1,
                'created_at' => '2020-03-31 13:50:44',
                'updated_at' => '2020-03-31 13:50:44',
                'created_by' => 1,
                'updated_by' => 1,
            ),
        ));
        DB::statement('SET FOREIGN_KEY_CHECKS = 1;');
        
    }
}