name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: laravelpwd
          MYSQL_DATABASE: laravel
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install Locales
      run: |
        sudo apt-get update
        sudo apt-get install locales
        sudo sed -i 's/# es_AR.UTF-8 UTF-8/es_AR.UTF-8 UTF-8/' /etc/locale.gen
        sudo locale-gen
    - name: Create Database
      run: mysql -uroot -h127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -plaravelpwd -e 'CREATE DATABASE IF NOT EXISTS laravel;'
    - name: Run Migration
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }} 
      run: php artisan migrate:fresh --seed -v
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }} 
      run: vendor/bin/phpunit
